# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-embeddedlinux"
BBFILE_PATTERN_meta-embeddedlinux = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-embeddedlinux = "6"

LAYERDEPENDS_meta-embeddedlinux = "core"
LAYERSERIES_COMPAT_meta-embeddedlinux = "kirkstone"

# Switch this image to systemd so systemctl is available.
DISTRO_FEATURES:append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
VIRTUAL-RUNTIME_dev_manager = "udev"
